name: CI

env:
  LLVM_VERSION: 19

# Controls when the workflow will run
on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      llvm_version:
        description: "LLVM version"
        default: "19"

jobs:
  windows:
    strategy:
      matrix:
        include:
          - runner: windows-11-arm
            build-type: Release
            package_json_arch: "arm64"
            label: bun-webkit-windows-arm64
          - runner: windows-11-arm
            build-type: Debug
            package_json_arch: "arm64"
            label: bun-webkit-windows-arm64-debug

    runs-on: ${{ matrix.runner }}

    timeout-minutes: 90

    steps:
      - name: Install Scoop
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
          Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
          Join-Path (Resolve-Path ~).Path "scoop\shims" >> $Env:GITHUB_PATH

      - name: Install LLVM and Ninja
        run: |
          scoop install ninja

      - uses: cygwin/cygwin-install-action@006ad0b0946ca6d0a3ea2d4437677fa767392401

      - uses: actions/checkout@v4
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            /*
            !LayoutTests/
            !JSTests/

      - name: Build WebKit
        run: |
          $env:Path = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\ARM64\;" + $env:Path
          $env:WEBKIT_OUTPUT_DIR = "bun-webkit"
          $env:BUN_WEBKIT_VERSION = "${{ github.sha }}"
          $env:CMAKE_BUILD_TYPE = "${{matrix.build-type}}"
          $env:PACKAGE_JSON_LABEL = "${{matrix.label}}"
          $env:GITHUB_SHA = "${{ github.sha }}"
          $env:PACKAGE_JSON_ARCH = "${{matrix.package_json_arch}}"
          $env:GITHUB_REPOSITORY = "${{ github.repository }}"
          ./windows-release.ps1
  
      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.label}}
          path: bun-webkit.tar.gz
